const config = {
  //BASE_URL: 'http://localhost:4000/api',
  // BASE_URL: 'https://xj84g1kx-3001.inc1.devtunnels.ms/api',
  CONTROLLS: [
    'single_line',
    'multi_line',
    'Number',
    'Name',
    'Email',
    'Address',
    'Phone',
    'Unique_ID',
    'Date',
    'Time',
    'Date-Time',
    'Checkbox',
    'section',
    'dropdown',
    'Radio',
    'Image Upload',
    'File Upload',
    'Description',
    'Star-Rating',
    'Avatar',
    'Circular Image',
    'Icon',
    'Button',
    'Toggle',
    'URL',
    'Close Button',
    'Button Dropdown',
    'Toggle Button',
    'Link',
    'Link List',
    'lookup',
    // "gender",

    'video',

    'url',
  ],
};

export default config;
