const config = {
  BASE_URL: 'http://localhost:3001/api',
  //BASE_URL: 'http://192.168.1.50:9966/api',

  CONTROLLS: [
    'single_line',
    'Multi_Line',
    'Number',
    'Email',
    'Date',
    'Time',
    'Date-Time',
    'dropdown',
    'Image Upload',
    'Star-Rating',
    'Link',
    'lookup',
    // 'Name',
    // 'Address',
    // 'Description',
    // 'Phone',
    // 'Unique_ID',
    // 'Checkbox',
    // 'section',
    // 'Radio',
    // 'File Upload',
    // 'Button',
    // 'Toggle',
    // 'URL',
    // 'Close Button',
    // 'Button Dropdown',
    // 'Toggle Button',
    // 'Link List',
    // 'Toggle Link',
    // 'Button Groups',
    // 'Color Input',
    // 'File Button',
    // 'File Dropzone',
    // 'File Input',
    // 'Microphone',
    // 'Scanner',
    // 'Signature',
    // 'Timer',
    // 'Chat',
    // 'Annotation Text',
    // 'Text Input',
    // 'Form',
    // 'Select',
    // 'Image',
    // 'Editable Text',
    // 'Editable TextArea',
    // 'Password',
    // 'Comment',
    // "gender",

    // "video",
  ],
};

export default config;
