const config = {
  // BASE_URL: 'http://localhost:5001/api',
  BASE_URL: 'http://192.168.1.50:9966/api',
  CONTROLLS: [
    'single_line',
    'Multi_Line',
    'Number',
    'Name',
    'Email',
    'Address',
    'Phone',
    'Unique_ID',
    'Date',
    'Time',
    'Date-Time',
    'Checkbox',
    'section',
    'dropdown',
    'Radio',
    'Image Upload',
    'File Upload',
    'Description',
    'Star-Rating',
    'Button',
    'Toggle',
    'URL',
    'Close Button',
    'Button Dropdown',
    'Toggle Button',
    'Link',
    'Link List',
    'Toggle Link',
    'Button Groups',
    'Color Input',
    'File Button',
    'File Dropzone',
    'File Input',
    'Microphone',
    'Scanner',
    'Signature',
    'Timer',
    'Chat',
    'Annotation Text',
    'Text Input',
    'Form',
    'Select',
    'Image',
    'Editable Text',
    'Editable TextArea',
    'Password',
    'Comment',
    'lookup',
    // "gender",

    // "video",
  ],
};

export default config;
